IITJHealthCare/HealthCentre/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('register', views.register, name = "register"),
    path('doctors', views.doctors, name = "doctors"),
    path('login', views.login, name = "login"),
    path('emergency', views.emergency, name = "emergency"),
    path('logout', views.logout, name = "logout"),
    path('contactus', views.contactus, name = "contactus"),
    path('onlineprescription', views.onlineprescription, name = "onlineprescription")
]

IITJHealthCare/IITJHealthCare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('HealthCentre.urls')),
    path('admin/', admin.site.urls),
    path('medicalstore/', include(('MedicalStore.urls', 'MedicalStore'), namespace = "MedicalStore"))
]

IITJHealthCare/MedicalStore/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('search', views.search, name = "search")
]

IITJHealthCare/HealthCentre/models.py
from django.db import models
from Crypto.Hash import SHA256
from codecs import encode,decode

class Doctor(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(unique = True, max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    specialization = models.CharField(max_length = 100)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email + " Specialization : " + self.specialization

class Patient(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    rollNumber = models.CharField(unique = True, max_length = 8)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email

class Prescription(models.Model):
    prescriptionText = models.CharField(max_length = 2000, default = "")
    doctor = models.ForeignKey(Doctor, related_name = "doctorRecords", on_delete = models.CASCADE)
    patient = models.ForeignKey(Patient, related_name = "patientRecords", on_delete = models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add = True)
    isNew = models.BooleanField(default = True)
    isCompleted = models.BooleanField(default = False)
    symptoms = models.CharField(max_length = 2000)

    def __str__(self):
        return "\nDoctor :" + str(self.doctor) + "\n\nPatient :" + str(self.patient) + "\n\nPrescription : \n\n" + self.prescriptionText + "\n\n"


def passwordHasher(userPassword):
    """Function to return the hash of the password using SHA-256. Input is the password of the user in string."""
    userPassword = userPassword
    SHA256Engine = SHA256.new()
    userPassword = userPassword.encode()
    SHA256Engine.update(userPassword)
    passwordHash = SHA256Engine.digest()
    passwordHash = encode(passwordHash, 'hex')
    passwordHash = decode(passwordHash, 'utf-8')
    return passwordHash


def emailHasher(userEmail):
    """Function to return the hash of the email using SHA-256. Input is the email of the user in string."""
    userEmail = userEmail
    SHA256Engine = SHA256.new()
    userEmail = userEmail.encode()
    SHA256Engine.update(userEmail)
    emailHash = SHA256Engine.digest()
    emailHash = encode(emailHash, 'hex')
    emailHash = decode(emailHash, 'utf-8')
    return emailHash

IITJHealthCare/HealthCentre/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Doctor, Patient, Prescription, passwordHasher, emailHasher
from django.db.models import Count, Q

# Create your views here.

def index(request):
    """ Function for displaying main page of website. """

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"HealthCentre/index.html")
    return responseHeadersModifier(response)


def register(request):
    """ Function for registering a student into the portal. """

    # If the user wants the page to get displayed
    if request.method == "GET":

        # Editing response headers so as to ignore cached versions of pages
        response =  render(request,"HealthCentre/registrationPortal.html")
        return responseHeadersModifier(response)

    # If the user wants to submit his/her information
    elif request.method == "POST":

        # Extracting the user information from the post request
        userFirstName = request.POST["userFirstName"]
        userLastName = request.POST["userLastName"]
        userEmail = request.POST["userEmail"]
        userRollNo = request.POST["userRollNo"]
        userAddress = request.POST["userAddress"]
        userContactNo = request.POST["userContactNo"]
        userPassword = request.POST["userPassword"]
        userConfirmPassword = request.POST["userConfirmPassword"]

        # If both the passwords match
        if userPassword == userConfirmPassword:

            name = userFirstName + " " + userLastName

            # Encrypting password to store inside database
            passwordHash = passwordHasher(userPassword)

            # Encrypting email to store inside database
            emailHash = emailHasher(userEmail)

            # Creating a patient object and saving insdie the database
            patient = Patient(name = name,rollNumber = userRollNo, email = userEmail, passwordHash = passwordHash, address = userAddress, contactNumber = userContactNo, emailHash = emailHash )
            patient.save()

            # Storing success message in the context variable
            context = {
                "message":"User Registration Successful. Please Login."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request, "HealthCentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

        # If the passwords given don't match
        else:
            # Storing failure message in the context variable
            context = {
                "message":"Passwords do not match.Please register again."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request,"HealthCentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

    # For any other method of request, sending back the registration page.
    else:

        # Editing response headers so as to ignore cached versions of pages
        response = render(request,"HealthCentre/registrationPortal.html")
        return responseHeadersModifier(response)


def doctors(request):
    """Function to send information about the doctors available to the user. """

    # Storing doctors available in the context variable
    context = {
        "doctors" : Doctor.objects.all()
    }

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"HealthCentre/doctors.html",context)
    return responseHeadersModifier(response)


def login(request):
    """ Function for logging in the user. """

    # If the request method is post
    if request.method == "GET":
        try:

            # If the user is already logged in inside of his sessions, and is a doctor, then no authentication required
            if request.session['isLoggedIn'] and request.session['isDoctor']:

                # Accessing the doctor user and all his/her records
                doctor = Doctor.objects.get(emailHash = request.session['userEmail'])
                records = doctor.doctorRecords.all()

                # Getting the count of the new prescriptions pending
                numberNewPendingPrescriptions = doctor.doctorRecords.aggregate(newPendingPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = False) ) ))['newPendingPrescriptions']

                # Storing the same inside the session variables
                request.session['numberNewPrescriptions'] = numberNewPendingPrescriptions

                # Storing the required information inside the context variable
                context = {
                    "message" : "Successfully Logged In.",
                    "isAuthenticated" : True,
                    "user": records.order_by('-timestamp')
                }

                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/userDoctorProfilePortal.html", context)
                return responseHeadersModifier(response)

            # If the user is already logged in inside of his sessions, and is a patient, then no authentication required
            elif request.session['isLoggedIn'] and (not request.session['isDoctor']):

                # Accessing the patient user and all his/her records
                patient = Patient.objects.get(emailHash = request.session['userEmail'])
                records = patient.patientRecords.all()

                # Getting the count of the new prescriptions pending
                numberNewPrescriptions = patient.patientRecords.aggregate(newCompletedPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = True) ) ) )['newCompletedPrescriptions']

                # Storing the same inside the session variables
                request.session['numberNewPrescriptions'] = numberNewPrescriptions

                # Updating the completed records
                for record in records:
                    if record.isCompleted:
                        record.isNew = False
                        record.save()

                # Storing the required information inside the context variable
                context = {
                    "message" : "Successfully Logged In.",
                    "isAuthenticated" : True,
                    "user": records.order_by('-timestamp')
                    }

                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/userPatientProfilePortal.html", context)
                return responseHeadersModifier(response)

            else:
                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/loginPortal.html")
                return responseHeadersModifier(response)

        # If any error occurs, sending back a new blank page
        except:

            # Editing response headers so as to ignore cached versions of pages
            response = render(request,"HealthCentre/loginPortal.html")
            return responseHeadersModifier(response)

    # If the request method is post
    elif request.method == "POST":

        # Extracting the user information from the post request
        userName = request.POST["useremail"]
        userPassword = request.POST["userpassword"]

        # If such a patient exists
        try:
            patient = Patient.objects.get(email = userName)

            # Storing required session information
            request.session['isDoctor'] = False

        # Otherwise trying if a doctor exists
        except Patient.DoesNotExist:
            try:
                doctor = Doctor.objects.get(email = userName)

                # Storing required session information
                request.session['isDoctor'] = True

            # If no such doctor or patient exists
            except Doctor.DoesNotExist:

                # Storing message inside context variable
                context = {
                    "message":"User does not exist.Please register first."
                }

                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/loginPortal.html", context)
                return responseHeadersModifier(response)

        # Getting the hash of user inputted password
        passwordHash = passwordHasher(userPassword)

        # If the logged in user is a doctor
        if request.session['isDoctor']:

            # Accessing all records of doctor
            records = doctor.doctorRecords.all()

            # Getting the count of new prescriptions
            numberNewPendingPrescriptions = doctor.doctorRecords.aggregate(newPendingPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = False) ) ))['newPendingPrescriptions']

            # Storing the same inside request variable
            request.session['numberNewPrescriptions'] = numberNewPendingPrescriptions

            # If the inputted hash and the original user password hash match
            if passwordHash == doctor.passwordHash:

                # Storing required information in session variable of request
                request.session['isLoggedIn'] = True
                request.session['userEmail'] = doctor.emailHash
                request.session['Name'] = doctor.name

                # Redirecting to avoid form resubmission
                # Redirecting to home page
                # Editing response headers so as to ignore cached versions of pages
                response = HttpResponseRedirect(reverse('index'))
                return responseHeadersModifier(response)

            # Else if the password inputted is worng and doesn't match

IITJHealthCare/HealthCentre/templates/HealthCentre/contactus.html
{% extends "HealthCentre/layout.html" %}

{% block title %}
IITJ Health Centre
{% endblock %}

{% block bodytag %}

  {% load static %}
  <body background="{% static 'HealthCentre/images/i6.jpg' %}" style="background-size: auto auto;">

{% endblock %}

{% block body %}
    <br>

    <div class="jumbotron jumbotron-fluid" style = "margin-left:5%;margin-right:5%;background:rgba(0,0,0,0.6);color:white;">
        <div class="container">

            <h1 >Address</h1>

            <p class="lead">Opposite Faculty Residential Building, IIT Jodhpur, Karwar, Jodhpur, Rajasthan</p>
            <button class="btn btn-info" >Pin Code : 342037</button>

            <br>
            <br>

            <h1>Email</h1>

            <p class="lead">Suggestions and feedback are thoroughly welcomed.</p>
            <button class="btn btn-info" >healthcentre@iitj.ac.in</button>

            <br>
            <br>

            <h1 >Reception Contact Numbers</h1>

            <p class="lead">Please feel free to call us anytime. 24 x 7 Helpline Availability.</p>
            <button class="btn btn-info" >Contact Numbers : 0141-3562834, 0141-35682104</button>

        </div>
    </div>

{% endblock %}

IITJHealthCare/HealthCentre/templates/HealthCentre/doctors.html
{% extends "HealthCentre/layout.html" %}

{% block title %}
IITJ Health Centre
{% endblock%}

{% block bodytag %}

  {% load static %}
  <body background="{% static 'HealthCentre/images/i6.jpg' %}" style="background-size: auto auto;">

{% endblock %}

{% block body %}

    <br>

    <h1 style="text-align:center;color:black;" class = "display-4">
      Available Doctors
    </h1>

    <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;border-color:black"></li>

    <br>
    <br>

    {% for doctor in doctors %}
        <div class="row container"style="margin: 0 auto;" >
            <div class="col-sm-12">
                <div class="card"style = "background:rgba(0,0,0,0.8);color:white;">
                    <div class="card-body">

                        <h5 class="card-title">Dr. {{ doctor.name }}</h5>
                        <li class="dropdown-divider"></li>
                        <p class="card-text"><pre style="color:white">Address        : {{ doctor.address }}<br>Email          : {{ doctor.email }}<br>Specialization : {{ doctor.specialization }}</pre></p>
                        <a href="#" class="btn btn-primary">Contact Number : {{ doctor.contactNumber }}</a>

                    </div>
                </div>
            </div>
        </div>

        <br>

    {% empty %}

        <h1 style="text-align:center;color:white" >
            Sorry! No doctors available right now. Please try again later!
        </h1>

    {% endfor %}

{% endblock %}

IITJHealthCare/HealthCentre/templates/HealthCentre/emergencyPortal.html
{% extends "HealthCentre/layout.html" %}

{% block title %}
IITJ Health Centre
{% endblock%}


{% block bodytag %}

  {% load static %}
  <body >

{% endblock %}

{% block body %}

    <br>

    <h1 style="text-align:center;color:red" class = "display-4">
        EMERGENCY

        <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;border-color:red"></li>

        <p class="lead">
            Either choose location from dropdown or type in text.
            <br>
            NO LOGIN REQUIRED
        </p>

    </h1>

    {% if message %}
        <div style="text-align:center;margin:0 auto;"class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <hr>

    <div class="container center_div" align ="center" width="300px">
        <form align="center" action = "{% url 'emergency' %}" method = "post">
            {% csrf_token %}

            <br>

            <div class="form-group">
                <select class="form-control" name="emergencyLocation">
                    <option>B1 Hostel         </option>
                    <option>B2 Hostel         </option>
                    <option>B3 Hostel         </option>
                    <option>G5 Hostel         </option>
                    <option>G6 Hostel         </option>
                    <option>Faculty Quarters  </option>
                    <option>Community Center  </option>
                    <option>Mess              </option>
                    <option>CSE Dept.         </option>
                    <option>EE Dept.          </option>
                    <option>ME Dept.          </option>
                    <option>Chemistry Dept.   </option>
                    <option>Football Ground   </option>
                    <option>VolleyBall Court  </option>
                    <option>BasketBall Court  </option>
                    <option>Cricket Ground    </option>
                    <option>Library           </option>
                    <option>Computer Centre   </option>
                    <option>Academic Building </option>
                </select>
            </div>

        <br>

        <button type="submit" class="btn btn-warning btn-lg" >CALL AMBULANCE</button>

        </form>
    </div>

    <hr>

    <div class="container center_div" align ="center" width="300px">
        <form align="center" action = "{% url 'emergency' %}" method = "post">
            {% csrf_token %}

            <br>

            <div class="form-group">

                <br>
                <div class="form-row">
                    <div class="col-12">
                        <input name="emergencyLocation" type="text" class="form-control" placeholder="Otherwise type location here.">
                    </div>
                </div>
                <br>

            </div>

            <br>
            <button type="submit" class="btn btn-warning btn-lg" >CALL AMBULANCE</button>
        </form>
    </div>

    <hr>

    <br>


{% endblock %}

IITJHealthCare/HealthCentre/templates/HealthCentre/index.html
{% extends "HealthCentre/layout.html" %}


{% block title %}
  IITJ Health Centre
{% endblock %}


{% block style %}

    .carousel-item{
        height: 500px;
      }
    .carousel-item img{
        height: 500px;
      }

{% endblock %}


{% block bodytag %}

    {% load static %}
    <body background="{% static 'HealthCentre/images/i6.jpg' %}" style="background-size: auto auto;">

{% endblock %}


{% block body %}

    <div style="text-align:center;margin: 0 auto;"class="alert alert-danger" role="alert">
        Swine Flu Outbreak in Jodhpur!! Get a precautionary checkup immediately!!
    </div>

    <div style="background-color:#eae8b2"  class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="{% static 'HealthCentre/images/jdh2.jpg' %}" class="d-block w-100 " alt="Mehrangarh Fort Jodhpur" >
                <div class="carousel-caption d-none d-md-block ">
                    <h5>Welcome To IIT Jodhpur Health Centre</h5>
                    <p>Good health and good sense are two of life's greatest blessings.</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{% static 'HealthCentre/images/jdh6.jpg' %}" class="d-block w-100 " alt="IIT Jodhpur Wall" >
                <div class="carousel-caption d-none d-md-block">
                    <h5>To enjoy the glow of good health, you must exercise - Gene Tunney</h5>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{% static 'HealthCentre/images/jdh7.jpg' %}" class="d-block w-100 " alt="IIT Jodhpur Main Gate" >
                <div class="carousel-caption d-none d-md-block">
                    <h5>To enjoy the glow of good health, you must exercise - Gene Tunney</h5>
                </div>
            </div>

        </div>

        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

    </div>
    {% if request.session.isLoggedIn %}
      {% else %}
      <div class="jumbotron" style="margin: 0 auto;">
          <h1 class="display-4">Hey there! Haven't registered yet?!</h1>
          <p class="lead">Register yourself today and get access to all the benefits of the Health Centre!</p>
          <hr class="my-4">
          <p>You must be a member of IIT Jodhpur to have access to this facility.</p>
          <a class="btn btn-primary btn-lg" href="{% url 'register' %}" role="button">Register</a>
      </div>
    {% endif %}

    <div>
        <hr class="my-4">
        <h1 class ="display-3"style="text-align:center;color:black">BENEFITS</h1>
        <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;border-color:black"></li>

        <div class="row"style="margin: 0 auto;" >

            <div class="col-sm-6" style = "margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Medical Store </h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Avail benefits of online medical store!</p>
                        <a href="{% url 'MedicalStore:index' %}" class="btn btn-primary">MEDICAL STORE</a>

                    </div>
                </div>
            </div>

            <div class="col-sm-6" style="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Emergency Ambulance</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Get immediate ambulance in emergency situation.</p>
                        <a href="{% url 'emergency' %}" class="btn btn-primary">EMERGENCY</a>

                    </div>
                </div>
            </div>

      </div>

        <div class="row"style="margin: 0 auto;" >

            <div class="col-sm-6" style ="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Online Prescription</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Get online hassle-free prescription from doctor.</p>
                        <a href="{% url 'onlineprescription' %}" class="btn btn-primary">ONLINE PRESCRIPTION</a>

                    </div>
                </div>
            </div>

            <div class="col-sm-6" style="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Contact Us</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">24 x 7 Help Line Availability.</p>
                        <a href="{% url 'contactus' %}" class="btn btn-primary">CONTACT US</a>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <div id="Footer">
        <h6 style="text-align:center;color:black;background-color:#dddddd;margin: 0 auto;">
            <hr class="my-4"style="margin: 0 auto;" >
                ©2019 All Rights Reserved, IIT Jodhpur
                <br>
                <br>
        </h6>
    <div>

{% endblock %}

IITJHealthCare/HealthCentre/templates/HealthCentre/layout.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <title>{% block title %}{% endblock %}</title>
        <style>{% block style %}{% endblock %}</style>

        <script>
        if ( window.history.replaceState ) {
          window.history.replaceState( null, null, window.location.href );
        }
        </script>
    </head>

{% block bodytag %}
{% endblock %}

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent" >
        {% if request.session.isLoggedIn %}
            <a class="navbar-brand" href="/"><h3 style="color:black;text-align:center">Hi,{% if request.session.isDoctor %} Dr.{% endif %} {{ request.session.Name }}</h3></a>
        {% else %}
            <a class="navbar-brand" href="/"><h2 style="color:black;text-align:center">IIT Jodhpur Health Centre</h2></a>
        {% endif %}

        <img src="{% static 'HealthCentre/images/jdh10.png' %}" style="width:5%;height:5%;"></img>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}" style="color:black">Home <span class="sr-only">(current)</span></a>
                </li>

                {% if request.session.isLoggedIn %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black">Your Prescriptions <span class="badge badge-primary badge-pill">{{ request.session.numberNewPrescriptions }} NEW</span></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black">Login</a>
                      </li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Options
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{% url 'MedicalStore:index' %}">Medicine Store</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'doctors' %}">Doctors</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'contactus' %}">Contact Us</a>

                        {% if request.session.isLoggedIn %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        {% endif %}

                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'onlineprescription' %}" style="color:black">Online Prescription</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'emergency' %}" style="color:black"><span style="background-color:red" class="badge badge-secondary">EMERGENCY</span></a>
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'MedicalStore:search' %}">
              {% csrf_token %}
                <input name = "searchQuery" class="form-control mr-sm-2" type="search" placeholder="Search Medicine" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </nav>
    <li class="dropdown-divider" style="margin-top:0px;margin-bottom:0px;border-color:black"></li>

{% block body %}

{% endblock %}

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        </body>
    </html>